name: integration-tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [ assigned, opened, synchronize, reopened, labeled ]

jobs:
  test-compute-core:
    runs-on: self-hosted
    strategy:
      matrix:
        ruby-version: [ '2.7', '3.0', '3.1' ]
      # Integration tests from the same task cannot run in parallel yet due to cleanup
      max-parallel: 1

    steps:
      - uses: actions/checkout@v2.4.0
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        env:
          # Needs to be set up for self-hosted runners, see:
          # https://github.com/ruby/setup-ruby#using-self-hosted-runners
          # Image used in runners: summerwind/actions-runner
          ImageOS: ubuntu20
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: >-
          ./.github/scripts/setup_creds.sh &&
          bundle exec rake test:compute-core_compute

  test-compute-networking:
    runs-on: self-hosted
    strategy:
      matrix:
        ruby-version: [ '2.7', '3.0', '3.1' ]
      # Integration tests from the same task cannot run in parallel yet due to cleanup
      max-parallel: 1

    steps:
      - uses: actions/checkout@v2.4.0
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        env:
          # Needs to be set up for self-hosted runners, see:
          # https://github.com/ruby/setup-ruby#using-self-hosted-runners
          # Image used in runners: summerwind/actions-runner
          ImageOS: ubuntu20
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: >-
          ./.github/scripts/setup_creds.sh &&
          bundle exec rake test:compute-core_networking

  test-compute-instance_groups:
    runs-on: self-hosted
    strategy:
      matrix:
        ruby-version: [ '2.7', '3.0', '3.1' ]
      # Integration tests from the same task cannot run in parallel yet due to cleanup
      max-parallel: 1

    steps:
      - uses: actions/checkout@v2.4.0
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        env:
          # Needs to be set up for self-hosted runners, see:
          # https://github.com/ruby/setup-ruby#using-self-hosted-runners
          # Image used in runners: summerwind/actions-runner
          ImageOS: ubuntu20
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: >-
          ./.github/scripts/setup_creds.sh &&
          bundle exec rake test:compute-instance_groups

  test-compute-loadbalancing:
    runs-on: self-hosted
    strategy:
      matrix:
        ruby-version: [ '2.7', '3.0', '3.1' ]
      # Integration tests from the same task cannot run in parallel yet due to cleanup
      max-parallel: 1

    steps:
      - uses: actions/checkout@v2.4.0
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        env:
          # Needs to be set up for self-hosted runners, see:
          # https://github.com/ruby/setup-ruby#using-self-hosted-runners
          # Image used in runners: summerwind/actions-runner
          ImageOS: ubuntu20
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: >-
          ./.github/scripts/setup_creds.sh &&
          bundle exec rake test:compute-loadbalancing

  test-monitoring:
    runs-on: self-hosted
    strategy:
      matrix:
        ruby-version: [ '2.7', '3.0', '3.1' ]
      # Integration tests from the same task cannot run in parallel yet due to cleanup
      max-parallel: 1

    steps:
      - uses: actions/checkout@v2.4.0
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        env:
          # Needs to be set up for self-hosted runners, see:
          # https://github.com/ruby/setup-ruby#using-self-hosted-runners
          # Image used in runners: summerwind/actions-runner
          ImageOS: ubuntu20
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: >-
          ./.github/scripts/setup_creds.sh &&
          bundle exec rake test:monitoring

  test-storage:
    runs-on: self-hosted
    strategy:
      matrix:
        ruby-version: [ '2.7', '3.0', '3.1' ]
      # Integration tests from the same task cannot run in parallel yet due to cleanup
      max-parallel: 1

    steps:
      - uses: actions/checkout@v2.4.0
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        env:
          # Needs to be set up for self-hosted runners, see:
          # https://github.com/ruby/setup-ruby#using-self-hosted-runners
          # Image used in runners: summerwind/actions-runner
          ImageOS: ubuntu20
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: >-
          ./.github/scripts/setup_creds.sh &&
          bundle exec rake test:storage

  test-pubsub:
    runs-on: self-hosted
    strategy:
      matrix:
        ruby-version: [ '2.7', '3.0', '3.1' ]
      # Integration tests from the same task cannot run in parallel yet due to cleanup
      max-parallel: 1

    steps:
      - uses: actions/checkout@v2.4.0
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        env:
          # Needs to be set up for self-hosted runners, see:
          # https://github.com/ruby/setup-ruby#using-self-hosted-runners
          # Image used in runners: summerwind/actions-runner
          ImageOS: ubuntu20
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: >-
          ./.github/scripts/setup_creds.sh &&
          bundle exec rake test:pubsub

  test-sql:
    runs-on: self-hosted
    strategy:
      matrix:
        ruby-version: [ '2.7', '3.0', '3.1' ]
      # Integration tests from the same task cannot run in parallel yet due to cleanup
      max-parallel: 1

    steps:
      - uses: actions/checkout@v2.4.0
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        env:
          # Needs to be set up for self-hosted runners, see:
          # https://github.com/ruby/setup-ruby#using-self-hosted-runners
          # Image used in runners: summerwind/actions-runner
          ImageOS: ubuntu20
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: >-
          ./.github/scripts/setup_creds.sh &&
          bundle exec rake test:sql
